apiVersion: v1                  # Uses the core Kubernetes API version v1.
kind: PersistentVolumeClaim     # Declares this resource is a PersistentVolumeClaim (PVC).
metadata:
  name: k8s-pvc                   # The name of this PVC object is "pvc-1".
spec:
  storageClassName: gp2         # Requests storage from the "gp2" StorageClass (commonly AWS EBS gp2 volumes).
  accessModes:
    - ReadWriteOnce             # The volume can be mounted as read/write by a single node at a time.
  resources:
    requests:
      storage: 2Gi              # Requests 2 GiB of persistent storage capacity.

