apiVersion: v1                  # This resource uses the core Kubernetes API version v1.
kind: Secret                     # Declares the type of resource: a Secret.
metadata:
  name: bbapp-db-secret        # The name of this Secret object, here it's "bankapp-db-secret".
type: Opaque                     # "Opaque" means this secret stores arbitrary user-defined data.
data:                            # The section where key-value pairs of sensitive data are stored.
  DB_USER: cm9vdA==              # Base64-encoded value for "root" (database username).
  DB_PASSWORD: YWRtaW4xMjM=      # Base64-encoded value for "admin123" (database password).
  DB_NAME: Y3VzdG9tZXJz          # Base64-encoded value for "customers" (database name).

